version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.READER_TOKEN}}

updates:
  - package-ecosystem: npm
    directory: '/'
    registries:
      - npm-github
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    groups:
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
        update-types:
          - 'minor'
          - 'patch'
      designsystem:
        patterns:
          - '@navikt/aksel-*'
          - '@navikt/ds-*'
        update-types:
          - 'minor'
          - 'patch'
      storybook:
        patterns:
          - 'storybook'
          - '@storybook/*'
        update-types:
          - 'minor'
          - 'patch'
      linting:
        patterns:
          - 'eslint'
          - '@eslint/*'
          - 'eslint-config-*'
          - 'eslint-plugin-*'
          - 'prettier'
          - 'stylelint*'
          - 'lint-staged'
          - 'knip'
        update-types:
          - 'minor'
          - 'patch'
      other:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    groups:
      github:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
