compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: node-modules

npmScopes:
  navikt:
    npmAlwaysAuth: true
    npmRegistryServer: 'https://npm.pkg.github.com'
    npmPublishRegistry: 'https://npm.pkg.github.com'
    npmAuthToken: '${NPM_AUTH_TOKEN:-}'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: 'https://mskelton.dev/yarn-outdated/v2'

yarnPath: .yarn/releases/yarn-4.12.0.cjs
