export const UnderavsnittType = {
  OPPSUMMERING: 'OPPSUMMERING',
  FAKTA: 'FAKTA',
  FORELDELSE: 'FORELDELSE',
  VILKAR: 'VILKÅR',
  SARLIGEGRUNNER: 'SÆRLIGEGRUNNER',
  SARLIGEGRUNNER_ANNET: 'SÆRLIGEGRUNNER_ANNET',
};
