enum ProsessBeregningsgrunnlagAksjonspunktCode {
  FASTSETT_BEREGNINGSGRUNNLAG_ARBEIDSTAKER_FRILANS = '5038',
  VURDER_VARIG_ENDRET_ELLER_NYOPPSTARTET_NAERING_SELVSTENDIG_NAERINGSDRIVENDE = '5039',
  FASTSETT_BRUTTO_BEREGNINGSGRUNNLAG_SELVSTENDIG_NAERINGSDRIVENDE = '5042',
  FASTSETT_BEREGNINGSGRUNNLAG_TIDSBEGRENSET_ARBEIDSFORHOLD = '5047',
  FASTSETT_BEREGNINGSGRUNNLAG_SN_NY_I_ARBEIDSLIVET = '5049',
  VURDER_GRADERING_UTEN_BEREGNINGSGRUNNLAG = '5050',
  VURDER_DEKNINGSGRAD = '5087',
}

export default ProsessBeregningsgrunnlagAksjonspunktCode;
