export enum FaktaFordelBeregningAvklaringsbehovCode {
  FORDEL_BEREGNINGSGRUNNLAG = 'FORDEL_BG',
  VURDER_REFUSJON_BERGRUNN = 'VURDER_REFUSJONSKRAV',
  VURDER_NYTT_INNTKTSFRHLD = 'VURDER_NYTT_INNTKTSFRHLD',
}
