export enum KodeverkType {
  BEHANDLING_AARSAK = 'BehandlingÅrsakType',
  OVERFOERING_AARSAK_TYPE = 'OverføringÅrsak',
  FAGSAK_STATUS = 'FagsakStatus',
  FAGSAK_YTELSE = 'FagsakYtelseType',
  BEHANDLING_TYPE = 'BehandlingType',
  OPPTJENING_AKTIVITET_TYPE = 'OpptjeningAktivitetType',
  INNTEKTSKATEGORI = 'Inntektskategori',
  AKTIVITET_STATUS = 'AktivitetStatus',
  BEHANDLING_RESULTAT_TYPE = 'BehandlingResultatType',
  BEHANDLING_STATUS = 'BehandlingStatus',
  KONSEKVENS_FOR_YTELSEN = 'KonsekvensForYtelsen',
  AKTSOMHET = 'Aktsomhet',
  VEDTAK_RESULTAT_TYPE = 'VedtakResultatType',
  TILBAKEKR_VIDERE_BEH = 'VidereBehandling',
  HENDELSE_TYPE = 'HendelseType',
  HENDELSE_UNDERTYPE = 'HendelseUnderType',
  FARESIGNAL_VURDERING = 'FaresignalVurdering',
}
