export enum LønnsendringScenario {
  MANUELT_BEHANDLET = 'MANUELT_BEHANDLET',
  DELVIS_MÅNEDSINNTEKT_SISTE_MND = 'DELVIS_MÅNEDSINNTEKT_SISTE_MND',
  FULL_MÅNEDSINNTEKT_EN_MND = 'FULL_MÅNEDSINNTEKT_EN_MND',
  FULL_MÅNEDSINNTEKT_TO_MND = 'FULL_MÅNEDSINNTEKT_TO_MND',
}
