export enum SammenligningType {
  FL = 'SAMMENLIGNING_FL',
  SN = 'SAMMENLIGNING_SN',
  AT = 'SAMMENLIGNING_AT',
  AT_FL = 'SAMMENLIGNING_AT_FL',
  ATFLSN = 'SAMMENLIGNING_ATFL_SN',
  MIDLERTIDIG_INAKTIV = 'SAMMENLIGNING_MIDL_INAKTIV',
}
