export enum PeriodeÅrsak {
  NATURALYTELSE_BORTFALT = 'NATURALYTELSE_BORTFALT',
  ARBEIDSFORHOLD_AVSLUTTET = 'ARBEIDSFORHOLD_AVSLUTTET',
  NATURALYTELSE_TILKOMMER = 'NATURALYTELSE_TILKOMMER',
  ENDRING_I_REFUSJONSKRAV = 'ENDRING_I_REFUSJONSKRAV',
  ENDRING_I_AKTIVITETER_SØKT_FOR = 'ENDRING_I_AKTIVITETER_SØKT_FOR',
  REFUSJON_OPPHØRER = 'REFUSJON_OPPHØRER',
  GRADERING = 'GRADERING',
  GRADERING_OPPHØRER = 'GRADERING_OPPHØRER',
  UDEFINERT = '-',
}
