export enum ProsessBeregningsgrunnlagAvklaringsbehovCode {
  FASTSETT_BEREGNINGSGRUNNLAG_ARBEIDSTAKER_FRILANS = 'FASTSETT_BG_AT_FL',
  VURDER_VARIG_ENDRET_ELLER_NYOPPSTARTET_NAERING_SELVSTENDIG_NAERINGSDRIVENDE = 'VURDER_VARIG_ENDRT_NYOPPSTR_NAERNG_SN',
  VURDER_VARIG_ENDRET_ARBEIDSSITUASJON = 'VURDER_VARIG_ENDRT_ARB_SITSJN_MDL_INAKTV',
  FASTSETT_BRUTTO_BEREGNINGSGRUNNLAG_SELVSTENDIG_NAERINGSDRIVENDE = 'FASTSETT_BG_SN',
  FASTSETT_BEREGNINGSGRUNNLAG_TIDSBEGRENSET_ARBEIDSFORHOLD = 'FASTSETT_BG_TB_ARB',
  FASTSETT_BEREGNINGSGRUNNLAG_SN_NY_I_ARBEIDSLIVET = 'FASTSETT_BG_SN_NY_I_ARB_LIVT',
  VURDER_GRADERING_UTEN_BEREGNINGSGRUNNLAG = 'VURDER_GRADERING_UTEN_BG',
}
