export type KonsekvensForYtelsen =
  | 'FORELDREPENGER_OPPHØRER'
  | 'ENDRING_I_BEREGNING'
  | 'ENDRING_I_UTTAK'
  | 'ENDRING_I_FORDELING_AV_YTELSEN'
  | 'INGEN_ENDRING'
  | 'ENDRING_I_BEREGNING_OG_UTTAK'
  | '-';
