name: CI

on:
  push:
    branches: [ci/effektiviser-workflow]
  pull_request:

jobs:
  setup:
    name: Install & Cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.17.1
          cache: 'yarn'
          registry-url: https://npm.pkg.github.com/
          always-auth: true
          token: ${{ secrets.READER_TOKEN }}
      - uses: ./.github/actions/restore-caches
      - run: yarn install --immutable

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/restore-caches
      - run: yarn test

  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/restore-caches
      - run: yarn eslint .

  stylelint:
    name: Run Stylelint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/restore-caches
      - run: yarn stylelint .

  tsc:
    name: Run Typescript
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/restore-caches
      - run: yarn tsc

  prettier:
    name: Run Prettier
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/restore-caches
      - run: yarn prettier --check .

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/restore-caches
      - run: yarn build