name: CI

on:
  push:
    branches: [main]
  pull_request:

# Reusable YAML anchors for cache restore
x-restore-yarn-cache: &restore-yarn-cache
  name: Restore Yarn cache
  uses: actions/cache@v4
  with:
    path: |
      .yarn/cache
      **/node_modules
    key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
    restore-keys: |
      yarn-${{ runner.os }}-

x-restore-build-cache: &restore-build-cache
  name: Restore Nx/Lerna build cache
  uses: actions/cache@v4
  with:
    path: |
      .nx/cache
      .turbo
      .lerna-cache
    key: build-cache-${{ runner.os }}-${{ github.sha }}
    restore-keys: |
      build-cache-${{ runner.os }}-

jobs:
  setup:
    name: Install & Cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - <<: *restore-yarn-cache
      - <<: *restore-build-cache
      - run: yarn install --frozen-lockfile

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - <<: *restore-yarn-cache
      - <<: *restore-build-cache
      - run: yarn test

  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - <<: *restore-yarn-cache
      - <<: *restore-build-cache
      - run: yarn eslint .

  prettier:
    name: Run Prettier
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - <<: *restore-yarn-cache
      - <<: *restore-build-cache
      - run: yarn prettier --check .
