name: Valider pull request
on: [pull_request]
jobs:
  valid-pull-request:
    name: Valider pull request
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Hente kode
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sette yarn-config
        run: |
          yarn config set npmScopes.navikt.npmRegistryServer "https://npm.pkg.github.com"
          yarn config set npmScopes.navikt.npmAlwaysAuth true
          yarn config set npmScopes.navikt.npmAuthToken $NPM_AUTH_TOKEN
        env:
          NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Sette opp Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.8.0
          cache: 'yarn'

      - name: Installere dependencies
        run: yarn install --immutable

      - name: Bygg
        run: yarn build

      - name: Typescript and linting
        run: yarn stylelint && yarn eslint:changed && yarn tsc

      - name: Run test
        run: yarn test
