name: Valider pull request
on: [ pull_request ]
jobs:
  valid-pull-request:
    name: Valider pull request
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22.17.1
          registry-url: https://npm.pkg.github.com/
          always-auth: true

      - name: Configure GitHub Packages Auth
        run: echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > ~/.npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Installere dependencies
        run: yarn install --immutable

      - name: Bygg
        run: yarn build

      - name: Stylelint
        run: yarn stylelint

      - name: ESLint
        run: yarn eslint:changed

      - name: Typescript
        run: yarn tsc

      - name: Run test
        run: yarn test

  knip-it:
    name: Kjør knip
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22.17.1
          registry-url: https://npm.pkg.github.com/
          always-auth: true
          cache: 'yarn'

      - name: Configure GitHub Packages Auth
        run: echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > ~/.npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Installere dependencies
        run: yarn install --immutable

      - name: Run knip
        run: |
          yarn knip --no-exit-code --reporter=markdown > knip-report.md
          cat knip-report.md > $GITHUB_STEP_SUMMARY

      - name: Delete previous comments from knip
        continue-on-error: true
        run: gh pr comment ${{ github.event.pull_request.number }} --delete-last --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Post knip report
        run: |
          number_of_words=$(wc -w < knip-report.md)
          if [ $number_of_words -gt 3 ]; then        
            gh pr comment ${{ github.event.pull_request.number }} --body-file knip-report.md
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
