name: Valider pull request
on: [pull_request]
jobs:
  valid-pull-request:
    name: Valider pull request
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Sette opp Node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 18.8.0
          registry-url: https://npm.pkg.github.com/
          scope: '@navikt'
          cache: 'yarn'

      - name: Installere dependencies
        run: yarn install --ignore-optional --no-progress --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Bygg
        run: yarn build

      - name: Typescript and linting
        run: yarn less:lint && yarn eslint:changed && yarn tsc:changed

      - name: Run test
        run: yarn test:changed -- -- --maxWorkers=2
